<?php
/**
 * Copyright (c) 2009-2012 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Kiosked
 * @copyright   Copyright (c) 2009-2012 Vaimo AB
 */
?>
<?php
/**
 * @var $this Vaimo_Kiosked_Block_Adminhtml_Feed
 */

$feedUrl = $this->getFeedUrl();
$outputEveryProduct = $this->getOutputEveryProduct();
$adminConfigUrl = $this->getAdminConfigUrl();

?>
<?php if ($feedUrl !== null && $feedUrl !== ''): ?>
<div>
    The product feed url: <a href="<?php echo $this->getFeedUrl(); ?>" target="_blank"><?php echo $this->getFeedUrl(); ?></a>
</div>
<?php endif; ?>

<?php if ($outputEveryProduct): ?>
    <?php echo sprintf($this->__("The module is set to output every product. To be able to select which products that
        should be published to the feed you can change the setting in the <a href='%s'>configuration</a>.", $adminConfigUrl)); ?>
<?php endif; ?>

<div>
    <?php echo $this->getGridHtml() ?>
</div>
